"""add risk_state table

Revision ID: 41cde2ea07b5
Revises: 4dad4f1eecd3
Create Date: 2026-07-20 16:46:31.813657

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41cde2ea07b5"
down_revision: str | Sequence[str] | None = "4dad4f1eecd3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "risk_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("daily_reference_equity", sa.Float(), nullable=True),
        sa.Column("daily_reference_date", sa.Date(), nullable=True),
        sa.Column("daily_halted", sa.Boolean(), nullable=False),
        sa.Column("daily_halted_at", sa.DateTime(), nullable=True),
        sa.Column("daily_halt_observed_value", sa.Float(), nullable=True),
        sa.Column("sticky_halted", sa.Boolean(), nullable=False),
        sa.Column("halt_cause", sa.String(), nullable=True),
        sa.Column("halted_at", sa.DateTime(), nullable=True),
        sa.Column("halt_observed_value", sa.Float(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("risk_state")
    # ### end Alembic commands ###
